### ISSUE TITLE
Problem with consent banner & p.a.caching

### ISSUE THREAD

**Issue by laulaz** [collective/collective.privacy#11]
If you activate caching, consent banner keeps appearing, even if you Allowed / Blocked corresponding data use ... until you refresh your browser cache (or force reload).

**Comment by mpeeters** [comment]
This problem only happen with an external caching server like varnish.

**Comment by mpeeters** [comment]
Fixed by https://github.com/collective/collective.privacy/commit/d196c225d339d74fc18897d241980b236f7cd8ef
