### ISSUE TITLE
Strictly Plone 5+? (empty portal_privacy folder in Plone 4.3)

### ISSUE THREAD

**Issue by tobiasherp** [collective/collective.privacy#17]
Despite the Plone 5.0-5.2 support claim, I tried to install the add-on (v1.1.0b1) in my Plone 4.3 development instance.
It started up ok and seemed to install as well, but instead of a `portal_privacy` tool, I found just an empty folder of that name in my site root.

So this means, it is definitely incompatible with Plone 4.3, right?

**Comment by laulaz** [comment]
@tobiasherp It works great on Plone 5.
The product must be "activated" to display the banner consent, and there is unfortunately no control panel to do it.
You can enable the banner through the portal registry (Plone control panel > Configuration registry). The record to activate it is named `collective.privacy.solicit_consent`.

If you have more cookies to consent to (by default you only have legitimate analytics), you'll have to define them in your product zcml, as explained in the documentation.

Example:
```
  <gdpr:data_use_category
        name="enhanced_analytics"
        title="Enhanced analytics"
        description="Analytics that are used to improve the website that involve
                     tracking users"
        legal_basis="consent"
        identifier="collective.privacy.identifiers.CookieIdentifier"
        storage="collective.privacy.storage.CookieStorage"
        />
```
